title: Minimal theme
logo: /assets/img/logo.png
description: DSC 80 Final Project, Fall 2024\nBy: Eeshi Uppalapati
show_downloads: true
google_analytics:

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
